### ISSUE TITLE
FunkSVD finished abruptly

### ISSUE THREAD

**Issue by lbalby** [sisinflab/elliot#6]
I have tried to run FunkSVD on MovieLens100k but it does finish the execution.

**To Reproduce**
The screenshots of the running and config files used for reproducing what I did are as follows.

<img width="584" alt="Screen Shot 2021-03-08 at 13 52 27" src="https://user-images.githubusercontent.com/10508349/110353259-9c4ea380-8015-11eb-9864-d2a606b01772.png">
<img width="477" alt="Screen Shot 2021-03-08 at 13 52 50" src="https://user-images.githubusercontent.com/10508349/110353284-a2448480-8015-11eb-9a54-4c0f60cc24a6.png">

**Expected behavior**
The screenshot of the execution trace is as follows.

<img width="866" alt="Screen Shot 2021-03-08 at 13 57 07" src="https://user-images.githubusercontent.com/10508349/110353807-3e6e8b80-8016-11eb-873a-546d9d0920c8.png">

I am Python 3.7 on a MacOS Big Sur version 11.1

**Comment by vitowalteranelli** [comment]
Hi @lbalby, this is due to memory saturation since you have run the recommender in full batch mode. We have now enabled the batch_size mode with funkSVD. Download the last version of the master branch and insert the batch_size field into the FunkSVD model as follows:

```
experiment:
  dataset: movielens_100k
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_100k/dataset.tsv
  splitting:
    test_splitting:
      stretegy: random_subsampling
      test_ratio: 0.2
  top_k: 10
  evaluation:
    simple_metrics: [RMSE]
  models:
    FunkSVD:
      meta:
        save_recs: True
      batch_size: 512
      factors: 100
      lr: 0.05
      reg_w: 0.02
      reg_b: 0.02
```

Let us know!
